language: android
jdk:
  - oraclejdk8
node_js:
  - "6"
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - android-23
env:
  global:
    - "MAVEN_OPTS=-Xmx2536m -XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
before_install:
  - "npm install electron-packager -g"
  - "npm install cordova -g"
  - "env"
  - "echo 'MAVEN_OPTS = $MAVEN_OPTS'"
